# Generated by Django 5.2.1 on 2025-07-04 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_code_alter_studentprofile_roll_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('EEE', 'Electrical'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('ENG', 'English')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
