# Generated by Django 5.2.1 on 2025-07-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='batch',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
    ]
