# Generated by Django 5.2.1 on 2025-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_placement_placementapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementapplication',
            name='resume',
            field=models.URLField(help_text='Enter a link to your resume'),
        ),
    ]
