# Generated by Django 5.2.1 on 2025-07-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_notification_course_remove_notification_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
    ]
