# Generated by Django 5.2.1 on 2025-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')], default=1),
            preserve_default=False,
        ),
    ]
