# Generated by Django 5.2.1 on 2025-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_studentprofile_year_remove_subject_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='eligible_courses',
            field=models.ManyToManyField(related_name='eligible_placements', to='core.course'),
        ),
    ]
